### PR TITLE
AuditOne Audit Reports

### PR DESCRIPTION
**Pull request by rajaauditone**
These are the audit reports for the few audits done at AuditOne.

### CODE REVIEW

**Comment by wang1252** [comment]
@rajaauditone 

Thank you for submitting the reports.
There are a few points that need to be fixed.

- Severity lines.
In the reports/AuditOne/09-05-2023-Aurorafastbridge.md, line 7, 71, 122, 147,
you used `## High Risks, ## Medium Risks, ## Low Risks, ## Quality Assurance`

But, only following 5 severity lines are allowed in our format.

```
## High Risk
## Medium Risk
## Low Risk
## Gas Optimizations
## Informational
```

This is founded on other reports, too.
Please fix this point for all reports.

- Remove the `.DS_Store` files.

**Comment by rajaauditone** [comment]
Folder and documents updated based on feedback

**Comment by rajaauditone** [comment]
Updated to our team page and deleted .DS_Store. Yes our website is https://www.auditone.io/

**Review by wang1252 — APPROVED** [review]

**Comment by wang1252** [comment]
@rajaauditone 

Congratulations. Your reports are successfully registered to our platform.

**Comment by rajaauditone** [comment]
hey ! We just have coinlend report reflected on platform but not others. Can you look into it ? 

Thanks

**Comment by wang1252** [comment]
@rajaauditone 

Ah. Your reports(except Coinlend) are using CRLF line ending.
I fixed this to LF and added your other reports to our platform again.
Now, we can see all the reports.

**Comment by wang1252** [comment]
@rajaauditone 

Please take care to use the LF line ending for the further reports.

**Pull request merged**
