### PR TITLE
optimism governor audit report - zach obront

### PR DESCRIPTION
**Pull request by maueth**
report: https://github.com/zobront/audits/blob/main/reports/optgov.md

### CODE REVIEW

**Comment by wang1252** [comment]
@maueth 

Could you please update the following one?

```
## Gas Optimization --> ## Gas Optimization
```

**Comment by maueth** [comment]
@wang1252 changed 🚀

**Review by wang1252 — APPROVED** [review]
Good.

**Comment by wang1252** [comment]
This report has been registered!!

**Pull request merged**
