### PR TITLE
Brahma Audit Report - TRUST SECURITY

### PR DESCRIPTION
**Pull request by okolicodes7**
Pls review this @wang1252

### CODE REVIEW

**Comment by wang1252** [comment]
@okolicodes7 

- Line 152,  ` ## Medium Risk`, please remove the space at the beginning.
- Line 450, `## Informational Findings` -> `## Informational`
- Line 451, `  ### Explicit matching of enum values` remove the space at the beginning.

- As you can see in the readme, only 5 severities are supported. High Risk, Medium Risk, Low Risk, Gas Optimizations, Informational

The followings would be treated unknown, please move to one of the available severity section.

```
## Centralization risks
## CoW-Swap risks
## Governance-related risks
## Console-admin risks
## Gelato risks
```

- Rename `logo_450_225 (4).png` as `logo_450_225.png`

**Comment by okolicodes7** [comment]
Pls review this @wang1252 I have made the corrections

**Comment by wang1252** [comment]
@okolicodes7 

All good, except background color of logo_450_225.png.
Please set as #292634.

**Comment by okolicodes7** [comment]
Pls review this @wang1252 as the image was done using #292634

**Comment by trust1995** [comment]
I've double confirmed it is #292634 locally.
Thanks.

**Review by wang1252 — APPROVED** [review]

**Comment by wang1252** [comment]
@okolicodes7 @trust1995 

Congratulations!!
Your reports have been registered to Solodit.

**Pull request merged**
