### PR TITLE
Brahma audits

### PR DESCRIPTION
**Pull request by okolicodes7**
Pls @wang1252 I added two new reports.
Check it out.

### CODE REVIEW

**Comment by okolicodes7** [comment]
Pls @wang1252 I just added a new report

**Comment by wang1252** [comment]
@okolicodes7 
Remove the space at the front of line 777 in 2023-02-24-Satin.Exchange.md

```
 ### TRST-L-7 _derivedBalance() doesn’t properly apply boosted rewards based on voting power
```

**Comment by okolicodes7** [comment]
@wang1252 I have made the corrections

**Comment by wang1252** [comment]
@okolicodes7 

Unnecessary space has been removed.
But an empty file is added `Stella.md`. 
If it is not necessary one, please remove it.

**Comment by okolicodes7** [comment]
I have done as you instructed @wang1252
Check again

**Comment by okolicodes7** [comment]
Pls review @wang1252 I added a new report

**Review by wang1252 — APPROVED** [review]

**Pull request merged**
