### PR TITLE
Add Pashov first report + logo

### PR DESCRIPTION
**Pull request by nisedo**
If everything is all right I will add all his other reports step by step (I asked him on Twitter for his permission)

### CODE REVIEW

**Comment by wang1252** [comment]
@nisedo 

I can't find the official site of Pashov.
Please let us know the site url.

**Comment by nisedo** [comment]
@wang1252 https://github.com/pashov/audits

**Comment by wang1252** [comment]
@nisedo 

No problem in the md file.
But the logo image does not fit our theme.

`logo_450_225.png` will be displayed on the landing page, all other logs are not colorful.
Please fix this logo image to fit our theme.
image

**Comment by nisedo** [comment]
I made the color change on the 450 225 logo to fit your theme 👍

**Review by wang1252 — APPROVED** [review]

**Pull request merged**
