### PR TITLE
olympus dao audit report - zach obront

### PR DESCRIPTION
**Pull request by maueth**

### CODE REVIEW

**Comment by hans-solodit** [comment]
@wang1252 please check this PR

**Comment by wang1252** [comment]
@maueth 

I checked your PR and the md file is good.
But the logos are not our format, please update the logos.
- For the logo_256_256.png, make transparent background.
- For the logo_450_225.png, set the background color with other existing ones and put `zachobront`(the name of your site) at the right side of logo.
Please reference [Cyfrin](https://github.com/solodit/solodit_content/tree/main/reports/Cyfrin) logos.

Thank you.

**Comment by maueth** [comment]
@wang1252 could you review again ?

**Comment by wang1252** [comment]
@maueth 

The logo_256_256.png is good.
For the logo_450_225.png, please adjust the colors like [Cyfrin](https://github.com/solodit/solodit_content/blob/main/reports/Cyfrin/logo_450_225.png).
 - bg: #292634
 - logo: #a4a4a4
 - name text: #ffffff

**Comment by maueth** [comment]
@wang1252 I pushed a new update following the guidelines you pointed:

> bg: #292634
> logo: #a4a4a4
> name text: #ffffff

**Review by wang1252 — APPROVED** [review]
All good. Will be registered on the Solodit.

**Comment by wang1252** [comment]
@maueth 

Congratulations!!
Your reports have been registered on the Solodit.

**Pull request merged**
