### PR TITLE
Brahma audits

### PR DESCRIPTION
**Pull request by okolicodes7**
Pls @wang1252 review I added another report

### CODE REVIEW

**Comment by okolicodes7** [comment]
Pls @wang1252 review

**Comment by wang1252** [comment]
@okolicodes7 

Remove the space at the front of line 498.
```
 ### TRST-L-6 Strategy upgrade cooldown is set too low
```

**Comment by okolicodes7** [comment]
Done,
 pls review  @wang1252

**Comment by okolicodes7** [comment]
Just Added another report also  @wang1252

**Review by wang1252 — APPROVED** [review]

**Pull request merged**
